require("dotenv").config();

const {  
    WAKANDA_TOKEN_CONTRACT_ADDRESS, 
    VOTING_CONTRACT_ADDRESS, 
    API_URL,
    DEFAULT_ADDRESS,
    PORT,
    PRIVATE_KEY
} = process.env;

module.exports = {
    API_URL: API_URL,
    WAKANDA_TOKEN_CONTRACT_ADDRESS: WAKANDA_TOKEN_CONTRACT_ADDRESS,
    VOTING_CONTRACT_ADDRESS: VOTING_CONTRACT_ADDRESS,
    DEFAULT_ADDRESS: DEFAULT_ADDRESS,
    PORT: PORT,
    PRIVATE_KEY: PRIVATE_KEY,
}