require('dotenv').config();
const Web3 = require("web3");

const {  
    WAKANDA_TOKEN_CONTRACT_ADDRESS_LOCAL, 
    VOTING_CONTRACT_ADDRESS_LOCAL, 
    API_URL_LOCAL,
    WAKANDA_TOKEN_CONTRACT_ADDRESS_KOVAN, 
    VOTING_CONTRACT_ADDRESS_KOVAN, 
    API_URL_KOVAN,
    DEFAULT_ADDRESS,
    PORT
} = process.env;

module.exports = {
    API_URL: API_URL_LOCAL,
    WAKANDA_TOKEN_CONTRACT_ADDRESS: WAKANDA_TOKEN_CONTRACT_ADDRESS_LOCAL,
    VOTING_CONTRACT_ADDRESS: VOTING_CONTRACT_ADDRESS_LOCAL,
    DEFAULT_ADDRESS: DEFAULT_ADDRESS,
    PORT: PORT
}