require('dotenv').config();
const Web3 = require("web3");

const {  
    WAKANDA_TOKEN_CONTRACT_ADDRESS_LOCAL, 
    VOTING_CONTRACT_ADDRESS_LOCAL, 
    API_URL_LOCAL,
    WAKANDA_TOKEN_CONTRACT_ADDRESS_KOVAN, 
    VOTING_CONTRACT_ADDRESS_KOVAN, 
    API_URL_KOVAN_ALCHEMY,
    DEFAULT_ADDRESS,
    DEFAULT_ADDRESS_LOCAL,
    PORT,
    PRIVATE_KEY_KOVAN,
    PRIVATE_KEY_LOCAL
} = process.env;

module.exports = {
    API_URL: API_URL_KOVAN_ALCHEMY,
    WAKANDA_TOKEN_CONTRACT_ADDRESS: WAKANDA_TOKEN_CONTRACT_ADDRESS_KOVAN,
    VOTING_CONTRACT_ADDRESS: VOTING_CONTRACT_ADDRESS_KOVAN,
    DEFAULT_ADDRESS: DEFAULT_ADDRESS,
    PORT: PORT,
    PRIVATE_KEY: PRIVATE_KEY_KOVAN,
}