export const  WAKANDA_TOKEN_CONTRACT_ADDRESS = process.env.REACT_APP_WAKANDA_TOKEN_CONTRACT_ADDRESS;
export const  VOTING_CONTRACT_ADDRESS = process.env.REACT_APP_VOTING_CONTRACT_ADDRESS;
export const  API_URL = process.env.REACT_APP_API_URL;
export const  DEFAULT_ADDRESS = process.env.REACT_APP_DEFAULT_ADDRESS;
export const  PRIVATE_KEY = process.env.REACT_APP_PRIVATE_KEY;